import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-tariff-classification-origin-refund-recovery",
  "engine": "recovery",
  "title": "Tariff Classification & Origin Refund Recovery",
  "shortTitle": "Tariff Classification and Origin Refund Recovery",
  "tagline": "Identify duty refunds through corrected classification, origin qualification, exclusions, and timely customs protests.",
  "industry": "Customs Recovery",
  "buyer": "Importers and customs compliance teams",
  "uiPort": 4684,
  "apiPort": 5684,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Tariff Classification & Origin Refund Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds in one accountable workflow. Identify duty refunds through corrected classification, origin qualification, exclusions, and timely customs protests.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Tariff Classification & Origin Refund Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("product-master-ingestion","TCO01","Product master ingestion","Execute product master ingestion using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed product master ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Product master ingestion Reference","text","TCO01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("hts-classification-review","TCO02","HTS classification review","Execute hts classification review using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed hts classification review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","HTS classification review Reference","text","TCO02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("binding-ruling-library","TCO03","Binding ruling library","Execute binding ruling library using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed binding ruling library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Binding ruling library Reference","text","TCO03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("country-of-origin-analysis","TCO04","Country-of-origin analysis","Execute country-of-origin analysis using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed country-of-origin analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Country-of-origin analysis Reference","text","TCO04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("substantial-transformation-test","TCO05","Substantial transformation test","Execute substantial transformation test using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed substantial transformation test decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Substantial transformation test Reference","text","TCO05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("trade-agreement-qualification","TCO06","Trade agreement qualification","Execute trade agreement qualification using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed trade agreement qualification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Trade agreement qualification Reference","text","TCO06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("section-301-exclusion-mapping","TCO07","Section 301 exclusion mapping","Execute section 301 exclusion mapping using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed section 301 exclusion mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Section 301 exclusion mapping Reference","text","TCO07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("entry-line-ingestion","TCO08","Entry line ingestion","Execute entry line ingestion using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed entry line ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Entry line ingestion Reference","text","TCO08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("duty-recalculation","TCO09","Duty recalculation","Execute duty recalculation using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed duty recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Duty recalculation Reference","text","TCO09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("post-summary-correction","TCO10","Post-summary correction","Execute post-summary correction using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed post-summary correction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Post-summary correction Reference","text","TCO10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("protest-deadline-control","TCO11","Protest deadline control","Execute protest deadline control using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed protest deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Protest deadline control Reference","text","TCO11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("prior-disclosure-coordination","TCO12","Prior disclosure coordination","Execute prior disclosure coordination using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed prior disclosure coordination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Prior disclosure coordination Reference","text","TCO12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("refund-evidence-package","TCO13","Refund evidence package","Execute refund evidence package using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed refund evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Refund evidence package Reference","text","TCO13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("customs-response-tracking","TCO14","Customs response tracking","Execute customs response tracking using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed customs response tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Customs response tracking Reference","text","TCO14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]}),
feature("product-origin-analytics","TCO15","Product origin analytics","Execute product origin analytics using product catalogs, bills of material, HTS classifications, country of origin, trade agreements, entries, duties, rulings, protests, and refunds.","Produce a governed product origin analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Importer / Entry Population","text","Importer / Entry Population · Standard Case"],["caseReference","Product origin analytics Reference","text","TCO15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1071250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1296213],["domainDriver","Refund Basis","select","Classification change",["Classification change","Origin preference","Section 301 exclusion"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Product master ingestion case","HTS classification review case","Binding ruling library case","Country-of-origin analysis case","Substantial transformation test case"]})
]);
